In [2]:
import numpy as np

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [9]:
np.full(5, 2.5)

array([2.5, 2.5, 2.5, 2.5, 2.5])

In [12]:
a = np.array([1, 2, 3 ,4])
a

array([1, 2, 3, 4])

In [16]:
a[2] = 10

In [17]:
a

array([ 1,  2, 10,  4])

In [19]:
np.arange(3, 10)

array([3, 4, 5, 6, 7, 8, 9])

In [29]:
np.linspace(0, 1, 11)

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9, 1. ])

In [31]:
np.zeros((5, 2))

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [ ]:
n = np.array([
    [1, 2, 3],
    [3, 5, 6],
    [6, 8, 9],
])

In [46]:
n[0, 1] = 20

In [47]:
n

array([[ 1, 20,  3],
       [ 3,  5,  6],
       [ 6,  8,  9]])

In [49]:
n[2] = [1, 1, 1]

In [52]:
n

array([[ 1, 20,  3],
       [ 3,  5,  6],
       [ 1,  1,  1]])

In [56]:
n[:, 2] = [0, 1, 2]

In [57]:
n

array([[ 1, 20,  0],
       [ 3,  5,  1],
       [ 1,  1,  2]])

In [60]:
np.random.seed(2)
np.random.rand(5, 2)

array([[0.4359949 , 0.02592623],
       [0.54966248, 0.43532239],
       [0.4203678 , 0.33033482],
       [0.20464863, 0.61927097],
       [0.29965467, 0.26682728]])

In [61]:
np.random.seed(2)
np.random.randn(5, 2)

array([[-0.41675785, -0.05626683],
       [-2.1361961 ,  1.64027081],
       [-1.79343559, -0.84174737],
       [ 0.50288142, -1.24528809],
       [-1.05795222, -0.90900761]])

In [63]:
np.random.seed(2)
100 * np.random.rand(5, 2)

array([[43.59949021,  2.59262318],
       [54.96624779, 43.53223926],
       [42.03678021, 33.0334821 ],
       [20.4648634 , 61.92709664],
       [29.96546737, 26.68272751]])

In [72]:
np.random.seed(2)
np.random.randint(low=0, high=100, size=(5, 2))

array([[40, 15],
       [72, 22],
       [43, 82],
       [75,  7],
       [34, 49]])

In [74]:
a = np.arange(5)
a

array([0, 1, 2, 3, 4])

In [76]:
a * 2

array([0, 2, 4, 6, 8])

In [ ]:
a.std()

np.float64(1.4142135623730951)

In [85]:
n.min()

np.int64(0)