In [107]:
import numpy as np

In [108]:
def dot_product(u, v):
    assert u.shape[0] == v.shape[0]

    n = u.shape[0]

    result = 0.0
    for i in range(n):
        result = result + u[i] * v[i]

    return result

In [109]:
u = np.array([1, 2, 3, 4])
v = np.array([5, 6, 7, 8])

In [110]:
dot_product(u, v)

np.float64(70.0)

In [111]:
u.dot(v)

np.int64(70)

In [112]:
U = np.array([
    [2, 4, 5, 6],
    [1, 2, 1, 2],
    [3, 1, 2, 1]
])

In [113]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]

    numb_rows = U.shape[0]

    result = np.zeros(numb_rows)
    for i in range(numb_rows):
        result[i] = dot_product(U[i], v)

    return result

In [114]:
matrix_vector_multiplication(U, v)

array([117.,  40.,  43.])

In [115]:
U.dot(v)

array([117,  40,  43])

In [116]:
U @ v

array([117,  40,  43])

In [117]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    numb_rows = U.shape[0]
    numb_columns = V.shape[1]
    result = np.zeros((numb_rows, numb_columns))

    for i in range(numb_columns):
        result[:, i] = matrix_vector_multiplication(U, V[:, i])

    return result

In [118]:
V = np.array([
    [1, 2, 3, 1],
    [4, 6, 6, 3],
    [3, 8, 9, 3],
    [10, 11, 12, 4]
])

In [119]:
matrix_matrix_multiplication(U, V)

array([[ 93., 134., 147.,  53.],
       [ 32.,  44.,  48.,  18.],
       [ 23.,  39.,  45.,  16.]])

In [120]:
J = U @ V
J

array([[ 93, 134, 147,  53],
       [ 32,  44,  48,  18],
       [ 23,  39,  45,  16]])

In [121]:
U.dot(V)

array([[ 93, 134, 147,  53],
       [ 32,  44,  48,  18],
       [ 23,  39,  45,  16]])

In [122]:
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [123]:
I @ J

array([[ 93., 134., 147.,  53.],
       [ 32.,  44.,  48.,  18.],
       [ 23.,  39.,  45.,  16.]])

In [124]:
V

array([[ 1,  2,  3,  1],
       [ 4,  6,  6,  3],
       [ 3,  8,  9,  3],
       [10, 11, 12,  4]])

In [125]:
Vinv = np.linalg.inv(V)
Vinv

array([[ 8.33333333e-02, -5.90544162e-18, -2.50000000e-01,
         1.66666667e-01],
       [-1.50000000e+00,  1.06297949e-16,  5.00000000e-01,
        -4.00585790e-17],
       [ 1.02777778e+00, -3.33333333e-01, -8.33333333e-02,
         5.55555556e-02],
       [ 8.33333333e-01,  1.00000000e+00, -5.00000000e-01,
        -3.33333333e-01]])

In [126]:
Vinv @ V

array([[ 1.00000000e+00,  6.38378239e-16,  9.99200722e-16,
         3.33066907e-16],
       [-4.00585790e-16,  1.00000000e+00, -1.36888137e-15,
        -3.82278921e-16],
       [-6.93889390e-17, -7.63278329e-17,  1.00000000e+00,
        -8.32667268e-17],
       [ 7.77156117e-16,  4.99600361e-16,  2.22044605e-16,
         1.00000000e+00]])